[feature]: Integrate RIPE Atlas Probe Measurements Data Source
InternetHealthReport/internet-yellow-pages pull request #101
Opened 2023-12-25 00:41 UTC by mohamedawnallah

## Description
This PR integrates RIPE Atlas Measurements Data Source, adding the following relationships and node labels:
- `(:AtlasProbe)-[:PART_OF]->(:AtlasMeasurement)-[:TARGET]->(:DomainName)`
- `(:AtlasProbe)-[:PART_OF]->(:AtlasMeasurement)-[:TARGET]->(:IP)`

## Motivation and Context
Closes #81

## How Has This Been Tested?
I ran the `atlas_measurements.py` crawler and it successfully created the `AtlasMeasurement` Node Label and `TARGET`, and `PART_OF` relationship links.

## Recordings
https://github.com/InternetHealthReport/internet-yellow-pages/assets/69568555/842c5c6a-d90a-4263-bb19-3a3b145d49a1

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-12-26 03:46 UTC, m-appel requested changes
Thanks for the implementation! I added some comments.

I noticed that this crawler adds *a lot* of relationships (~21m), so I don't expect you to run it in its entirety for testing. I discussed a bit with Romain and we have some ideas to maybe reduce the number of relationships, but we will do that at a later point in time, so for now addressing just the few comments is fine.

2023-12-26 03:46 UTC, m-appel commented on iyp/crawlers/ripe/atlas_measurements.py
> +        prefixes = set()
Let's not create Prefix nodes from this crawler. We are unsure where Atlas actually gets this information from. Maybe we can add it later, but for now let's just keep it in the property.

2023-12-26 03:46 UTC, m-appel commented on iyp/crawlers/ripe/atlas_measurements.py
> +                ip_qid = ip_ids[probe_measurement_ip]
There are measurements with an empty string in the `resolved_ips` list, where this breaks ([example](https://atlas.ripe.net/api/v2/measurements/8350811)).

2023-12-26 04:25 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +            break
Aha yes 👍

2023-12-26 04:44 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                "domain": item.pop("target", None),
Yes, thanks for sharing this!

2023-12-26 04:47 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                "domain": item.pop("target", None),
I'm also thinking of configuring the `pre-commit` hooks in the CI this way we enforce all the rules implemented by the [`.pre-commit-config.yml`](https://github.com/InternetHealthReport/internet-yellow-pages/blob/main/.pre-commit-config.yaml) e.g running in the CI:
```bash
pre-commit run --all-files
```

2023-12-26 05:07 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +            sys.exit(f'Request to {response.url} failed with status: {response.status_code}')
Yes, this makes much sense. Acknowledged!

2023-12-26 05:20 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +            group_info = {
Certainly! Here's the updated comment with the code included:

---

The problem arises from data retrieved from the RIPE Atlas Measurement dataset. The `group` or `target` info is prefixed with `target/group`. When we attempt to flatten this data using the `_` delimiter, it triggers a Type Error Exception within the `flatdict` library.

For example, running the provided code snippet below generates an error:

```python
import flatdict
object = {"group": None, "group_id": None}
flatdict.FlatterDict(object, delimiter='_')
```

This error resembles the one shown:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 389, in __init__
    super(FlatterDict, self).__init__(value, delimiter, dict_class)
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 29, in __init__
    self.update(value)
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 356, in update
    [self.__setitem__(k, v) for k, v in dict(other or kwargs).items()]
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 356, in <listcomp>
    [self.__setitem__(k, v) for k, v in dict(other or kwargs).items()]
     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 420, in __setitem__
    raise TypeError(
TypeError: Assignment to invalid type for key group
```

This issue persists with the `target` information as well so I needed to flatten them out myself.

2023-12-26 05:20 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +            group_info = {
The problem arises from data retrieved from the RIPE Atlas Measurement dataset. The `group` or `target` info is prefixed with `target/group`. When we attempt to flatten this data using the `_` delimiter, it triggers a Type Error Exception within the `flatdict` library.

For example, running the provided code snippet below generates an error:

```python
import flatdict
object = {"group": None, "group_id": None}
flatdict.FlatterDict(object, delimiter='_')
```

This error resembles the one shown:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 389, in __init__
    super(FlatterDict, self).__init__(value, delimiter, dict_class)
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 29, in __init__
    self.update(value)
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 356, in update
    [self.__setitem__(k, v) for k, v in dict(other or kwargs).items()]
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 356, in <listcomp>
    [self.__setitem__(k, v) for k, v in dict(other or kwargs).items()]
     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohamedawnallah/Desktop/internet-yellow-pages/.venv/lib/python3.11/site-packages/flatdict.py", line 420, in __setitem__
    raise TypeError(
TypeError: Assignment to invalid type for key group
```

This issue persists with the `target` information as well so I needed to flatten them out myself.

2023-12-26 05:21 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +            group_info = {
That said I'm gonna update the comments in the code to let anyone who read the code why we extracted the information in this kind of format.

2023-12-26 05:29 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                        resolved_ips[i] = ipaddress.ip_address(resolved_ips[i]).compressed
There are some data points where the IP address is either "" or null.

2023-12-26 05:30 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                        resolved_ips[i] = None
Yes, I think so 👍

2023-12-26 05:56 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                        resolved_ips[i] = ipaddress.ip_address(resolved_ips[i]).compressed
It seems these absence values are not malformed IP addresses we should handle this in the `__get_all_resolved_ips` method instead.

2023-12-26 06:11 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                target_links.append({'src_id': probe_measurement_qid, 'dst_id': domain_qid, 'props': [self.reference]})
I got what you means regards adding the reference on the relationship link but could you please elaborate more on this: `Note that this requires many dict copies in the "compute first / push later" approach.` ?

2023-12-26 06:22 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                target_links.append({'src_id': probe_measurement_qid, 'dst_id': domain_qid, 'props': [self.reference]})
Do you mean, should we include the `reference` field when we compute or pre-compute the nodes rather than adding it during the computation of the links? Additionally, considering that the `result` field in the data result already contains the precise path (`https://atlas.ripe.net/api/v2/measurements/x`), could we potentially access it directly, making the addition of the `reference` field or updating `self.reference` with `/{id}` unnecessary?

2023-12-26 07:10 UTC, m-appel commented on iyp/crawlers/ripe/atlas_measurements.py
> +                "domain": item.pop("target", None),
That would be great! When I setup the github actions I did not (and still do not really) know how they work, so they actually don't check exactly the same things as the pre-commit hook.

2023-12-26 07:10 UTC, m-appel commented on iyp/crawlers/ripe/atlas_measurements.py
> +            group_info = {
I see! Yes that makes sense then and good idea to add a comment.

2023-12-26 07:23 UTC, m-appel commented on iyp/crawlers/ripe/atlas_measurements.py
> +                target_links.append({'src_id': probe_measurement_qid, 'dst_id': domain_qid, 'props': [self.reference]})
Regarding the first question: I made the mistake that I've updated the reference dict inside a for loop when computing the relationships, but since only a *reference* of the dict is stored in the list you actually only overwrite the url field of the same dict. For example

```python
links = list()
for x, y in nodes:
    self.reference['reference_url'] = ...
    links.append({'src_id': x, 'dst_id': y, 'props': [self.reference]})

self.iyp.batch_add_links(...)
```

would lead to all but one relationship having the wrong URL so a `self.reference.copy()` is needed instead. Or maybe there is a better way I don't know of :)

For the second question, even though it is a bit tedious I would prefer to update the `reference_url` field. The `result` field technically points to the *results* of the measurement, not the metadata. In addition, you have to know that this field exists to find it, and you have to know how to get to the metadata from there.
In general the `reference_url` should be as precise as possible, although this does not always work, but for Atlas it does quite well :)

2023-12-26 08:13 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                "domain": item.pop("target", None),
Okay I would love to submit PR for this!

2023-12-27 03:56 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                target_links.append({'src_id': probe_measurement_qid, 'dst_id': domain_qid, 'props': [self.reference]})
Yes this makes sense, Thanks for the explanation!

2023-12-27 04:57 UTC, mohamedawnallah commented on iyp/crawlers/ripe/atlas_measurements.py
> +                target_links.append({'src_id': probe_measurement_qid, 'dst_id': domain_qid, 'props': [self.reference]})
Yes this makes sense, Thanks!

2023-12-27 05:52 UTC, mohamedawnallah commented
Thank you, @m-appel, for the fantastic feedback. I've incorporated your suggestions and also updated the documentation.

2023-12-28 02:26 UTC, merged

2023-12-28 02:26 UTC, m-appel commented
Thanks, looks good to me!