CAIDA's IXP info and membership
InternetHealthReport/internet-yellow-pages pull request #113
Opened 2024-01-17 06:21 UTC by romain-fontugne

This adds CAIDA IXP information and IXP membership. It may adds some redundant links with PeeringDB but as it also adds new IXPs (found via HE) I wanted to make sure the links are consistent across all IXP.

## How Has This Been Tested?

Tried locally, the data seems properly imported to me.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-19 09:21 UTC, m-appel requested changes
I've added some comment :)
We should also update the README since there are dependencies. The `ix_asns` crawler depends on `ixs`, and `ixs` depends on the PeeringDB crawlers.

2024-01-19 09:21 UTC, m-appel commented on iyp/crawlers/caida/ixs.py
> +                ixp_qid = self.iyp.get_node('IXP', {'name': ix['name']})
The CAIDA ID is not actually an ID... There are several IXPs with two IDs now, And almost all of these actually have a PeeringDB ID attached to one of them:

```cypher
MATCH p = (i:IXP)-[:EXTERNAL_ID]->(a:CaidaIXID)
MATCH q = (i)-[:EXTERNAL_ID]->(b:CaidaIXID)
WHERE a <> b
MATCH x = (i)-[:EXTERNAL_ID]->(:PeeringdbIXID)
RETURN p,q,x
```

But, there is one example that has no PeeringDB ID:

```cypher
MATCH p = (i:IXP)-[:EXTERNAL_ID]->(a:CaidaIXID)
MATCH q = (i)-[:EXTERNAL_ID]->(b:CaidaIXID)
WHERE a <> b
AND NOT EXISTS {
  (i)-[:EXTERNAL_ID]->(:PeeringdbIXID)
}
RETURN p,q
```

Good thing is that the name is the same, so we do not create duplicate nodes, only multiple relationships for name and country.
Actually, if the name is not precisely the same, we may have multiple nodes for the logical same IXP, but that's a problem we can not solve I guess.

2024-01-24 07:57 UTC, romain-fontugne commented on iyp/crawlers/caida/ix-asns.py
> +
I didn't throw an exception here because anyways the first thing that happens in run is download the file and throw an exception if that doesn't work. So I thought that makes it a bit too redudant

2024-01-24 08:05 UTC, romain-fontugne commented on iyp/crawlers/caida/ixs.py
> +                ixp_qid = self.iyp.get_node('IXP', {'name': ix['name']})
yes, I think that is a problem from the data source. We shouldn't fix it in the crawler but we could use IYP to find those errors and report that to CAIDA, they will hopefully fix these errors.

2024-01-24 08:08 UTC, romain-fontugne commented on iyp/crawlers/caida/ixs.py
> +            if 'country' in ix:
interesting, I somehow prefer the code duplication, I feel that it makes each part of the code a bit more independent. But anyways either way works.

2024-01-24 08:16 UTC, m-appel commented on iyp/crawlers/caida/ixs.py
> +            if 'country' in ix:
It makes it independent, but it also invites different semantics if you forget to update both code blocks :P But yeah, both work so you do not _have_ to change address this.

2024-01-25 03:45 UTC, romain-fontugne commented on iyp/crawlers/caida/ix-asns.py
> +
Anyways I'll throw an exception here too

2024-01-25 05:55 UTC, romain-fontugne commented on iyp/crawlers/caida/ix-asns.py
> +NAME = 'caida.ix-asns'
fixed in [0645995](https://github.com/InternetHealthReport/internet-yellow-pages/pull/113/commits/06459953a756b2c3b0485ca465024ca566d40d50)

2024-01-25 05:55 UTC, romain-fontugne commented on iyp/crawlers/caida/ix-asns.py
> +
fixed in [0645995](https://github.com/InternetHealthReport/internet-yellow-pages/pull/113/commits/06459953a756b2c3b0485ca465024ca566d40d50)

2024-01-25 05:56 UTC, romain-fontugne commented on iyp/crawlers/caida/ixs.py
> +
fixed in [0645995](https://github.com/InternetHealthReport/internet-yellow-pages/pull/113/commits/06459953a756b2c3b0485ca465024ca566d40d50)

2024-01-25 05:56 UTC, romain-fontugne commented on iyp/crawlers/caida/ixs.py
> +            if ixp_qid is None and 'name' in ix:
fixed in [0645995](https://github.com/InternetHealthReport/internet-yellow-pages/pull/113/commits/06459953a756b2c3b0485ca465024ca566d40d50)

2024-01-25 05:56 UTC, romain-fontugne commented on iyp/crawlers/caida/ix-asns.py
> +        caida_ids = set()
fixed in [0645995](https://github.com/InternetHealthReport/internet-yellow-pages/pull/113/commits/06459953a756b2c3b0485ca465024ca566d40d50)

2024-01-25 05:59 UTC, romain-fontugne commented
Thanks for the comments. I have completely forgot about the README! :fearful:

2024-01-28 02:50 UTC, m-appel approved these changes
Thanks, looks good to me now.

2024-01-28 02:51 UTC, merged