Rov detection #83 issue
InternetHealthReport/internet-yellow-pages pull request #124
Opened 2024-02-07 21:00 UTC by MAVRICK-1

## Description
Solved the #83 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

@m-appel I was a pre-commit issue with the previous branch
so I closed that Pull request

2024-02-08 02:34 UTC, m-appel requested changes
Congratulations, you have a working crawler! :)

I've commented on a few nitpicks, once these are done this PR is good to be merged.

Btw. have you installed pre-commit locally? It should report the same problems as the GitHub runner when you commit, i.e., you do not have to wait for the output of the runner.

2024-02-08 02:34 UTC, m-appel commented on iyp/crawlers/rovista/validating_rov.py
> +        logging.info('Pushing nodes to neo4j...\n')
Remove the `\n`

2024-02-08 02:34 UTC, m-appel commented on iyp/crawlers/rovista/validating_rov.py
> +        tag_id_not_vali = self.iyp.get_node('Tag', {'label': 'Not Validating RPKI ROV'}, create=True)
`tag_id_not_valid` (`d` is missing)

2024-02-08 02:34 UTC, m-appel commented on iyp/crawlers/rovista/validating_rov.py
> +        tag_id_vali = self.iyp.get_node('Tag', {'label': 'Validating RPKI ROV'}, create=True)
`tag_id_valid` (`d` is missing)

2024-02-08 02:34 UTC, m-appel commented on iyp/crawlers/rovista/validating_rov.py
> +                links.append({'src_id': asn_qid, 'dst_id': tag_id_vali, 'props': [self.reference, entry]})
We do not need the ASN and label in the relationship properties, so you can just do
```python
'props': [self.reference, {'ratio': entry['ratio']}]
```

2024-02-08 02:34 UTC, m-appel commented on iyp/crawlers/rovista/validating_rov.py
> +                links.append({'src_id': asn_qid, 'dst_id': tag_id_not_vali, 'props': [self.reference, entry]})
Same as above

2024-02-08 02:34 UTC, m-appel commented on iyp/crawlers/rovista/validating_rov.py
> +        logging.info('Pushing links to neo4j...\n')
Remove the `\n`

2024-02-08 04:06 UTC, MAVRICK-1 commented
@m-appel Thanks for Your Guidance , I made the requested changes , and Sry for the numerous commits , I am new to using pre-commit . In the Future , I will strive to minimize the frequency of commits

2024-02-08 04:08 UTC, MAVRICK-1 commented
> Congratulations, you have a working crawler! :)
> 
> I've commented on a few nitpicks, once these are done this PR is good to be merged.
> 
> Btw. have you installed pre-commit locally? It should report the same problems as the GitHub runner when you commit, i.e., you do not have to wait for the output of the runner.

I was using codespace for that pre-commit was not working ;-)

2024-02-08 04:25 UTC, MAVRICK-1 commented
> Congratulations, you have a working crawler! :)
> 
> I've commented on a few nitpicks, once these are done this PR is good to be merged.
> 
> Btw. have you installed pre-commit locally? It should report the same problems as the GitHub runner when you commit, i.e., you do not have to wait for the output of the runner.

Have installed it but it's showing 

```
pre-commit : The term 'pre-commit' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
```

2024-02-09 01:30 UTC, m-appel approved these changes
Thanks, looks good to me now!

2024-02-09 01:32 UTC, merged