Added url2domain.py file. Fixes issue #32
InternetHealthReport/internet-yellow-pages pull request #33
Opened 2023-03-05 13:44 UTC by Yh010

2023-03-06 00:40 UTC, romain-fontugne commented
The url2domain file looks fine but you are also adding 23 unecessary files ./history/* ?

2023-03-06 02:07 UTC, Yh010 commented
Actually since .history/ wasnt included in the gitignore file, all the history was also getting committed. changed it now..pls have a look

2023-03-07 04:44 UTC, romain-fontugne commented
You are still pushing two history files.

2023-03-07 08:30 UTC, Yh010 commented
@romain-fontugne removed the history files now.

2023-03-12 11:32 UTC, romain-fontugne requested changes

2023-03-12 11:32 UTC, romain-fontugne commented on iyp/post/url2domain.py
> +            domain_qid = self.iyp.get_node_id('DomainName', 'name', domain)
this method doesn't exist :D

2023-03-12 11:32 UTC, romain-fontugne commented on iyp/post/url2domain.py
> +            domain_qid = self.iyp.get_node_id('DomainName', 'name', domain)
I guess you want mean batch_get_nodes, but then you shouldn't call it in the for loop. You can call it only once

2023-03-13 03:38 UTC, romain-fontugne approved these changes
thanks, looks good to me

2023-03-13 03:39 UTC, merged