Implemented crawler that crawls from InetIntel/Dataset-AS-to-Organization-Mapping repo
InternetHealthReport/internet-yellow-pages pull request #38
Opened 2023-04-04 16:59 UTC by roopeshsn

Implemented crawler that crawls from InetIntel/Dataset-AS-to-Organization-Mapping repo. The Sibling ASes and the "AS" website data are crawled from the repo.

Recently, the repo filesystem has changed. A few tweaks need to be made to the crawlers' code to work properly. I'll make the appropriate changes ASAP.

2023-04-17 07:59 UTC, romain-fontugne requested changes
Thanks for the PR, but I could run the code. It started but never finished.. Please my reviews

2023-04-23 14:26 UTC, roopeshsn commented on iyp/crawlers/inetintel/siblings_asdb.py
> +        df = pd.read_json(filename, orient='index')
Using Pandas makes it easier to read the JSON and process it in batches.

2023-04-23 14:28 UTC, roopeshsn commented on iyp/crawlers/inetintel/siblings_asdb.py
> +            lines.append([asn, url, sibling_asns])
Yeah, it will add all the sibling's asn. But after that, there is a check to find whether the relationships exist already.

2023-04-26 01:40 UTC, romain-fontugne requested changes
hey, I think the code is still doing something wrong. You are creating way too many links

2023-04-26 01:40 UTC, romain-fontugne commented on iyp/__init__.py
> +    def are_connected(self, src, dst, type):
please remove this if we are not using it

2023-04-26 01:40 UTC, romain-fontugne commented on iyp/crawlers/inetintel/siblings_asdb.py
> +                    batch_sibling_asns.add(int(sibling_asn))
I think you missed the point of the dataset. You put all the sibling ASNs of one batch in the same set. This set should be emptied for every iteration of the 'for index,...' loop. Add ```batch_sibling_asns = set()``` after line 90

2023-04-27 05:27 UTC, roopeshsn commented on iyp/__init__.py
> +    def are_connected(self, src, dst, type):
Sure

2023-04-27 05:36 UTC, roopeshsn commented on iyp/crawlers/inetintel/siblings_asdb.py
> +                    batch_sibling_asns.add(int(sibling_asn))
Yep, there is a bug in the code as you said.

2023-05-11 01:38 UTC, romain-fontugne approved these changes
Thanks, it seems to work now. I may clean a bit the code later

2023-05-11 01:38 UTC, merged