feat: Added a crawler that crawls and push ip prefixes from bgptools/…
InternetHealthReport/internet-yellow-pages pull request #48
Opened 2023-05-14 04:25 UTC by roopeshsn

…anycast-prefixes repo to IYP.

#42

2023-05-14 04:30 UTC, m-appel commented
Thanks, I will check it out soon!

2023-05-14 06:12 UTC, m-appel requested changes
Thanks for implementing this! Looks mostly very good, the only change I'd request that is not formatting / documentation is the updated `reference_url`. If you could change that, I think we are good to merge, although I will let Romain have a brief look as well beforehand.

2023-05-14 06:12 UTC, m-appel commented on iyp/crawlers/bgptools/README.md
> +### IPV4 and IPV6 prefixes
Anycast IPv4 and IPv6 prefixes

2023-05-14 06:12 UTC, m-appel commented on iyp/crawlers/bgptools/README.md
> +Connect Prefix to tag node meaning that an AS has been categorized according to the tag with a label `Anycast`.
Tag (uppercase) node, and the prefix has been categorized, not the AS :)

2023-05-14 06:12 UTC, m-appel commented on iyp/crawlers/bgptools/README.md
> +MATCH (p:Prefix {prefix: '43.249.213.0/24'})-[r:CATEGORIZED]-(t:Tag {label: 'Anycast'}) RETURN p, t
In general, we only specify an example relationship, not a full query.
I.e., remove the `MATCH` and `RETURN` parts as well as the variable names.

2023-05-14 06:12 UTC, m-appel commented on iyp/crawlers/bgptools/anycast_prefixes.py
> +        anycast_prefixes_data_url_formatted += "/master/anycatch-v4-prefixes.txt"
This URL should be the `reference_url` for the IPv4 prefixes, and the URL some lines below for the IPv6 prefixes. I know that the actual contents behind that link might change since the repository is updated, but we have this behavior at several places, so it should be okay and we are consistent.

2023-05-14 06:12 UTC, m-appel commented on iyp/crawlers/bgptools/anycast_prefixes.py
> +        # """Fetch data and push to IYP. """
Remove the """

2023-05-14 06:12 UTC, m-appel commented on run_all_crawlers.sh
> +#BGP.Tools tags, and prefixes
tags and anycast prefixes

2023-05-14 06:12 UTC, m-appel commented on iyp/crawlers/bgptools/anycast_prefixes.py
A general comment, which is more a nitpick than anything else, but it would be cool to use single quotes where possible. We setup a `pre-commit` command that automatically does code format checks and conversions (see the new CONTRIBUTING.md file).

2023-05-14 06:38 UTC, roopeshsn commented on iyp/crawlers/bgptools/README.md
> +- IPV4, and IPV6 prefixes
Sure

2023-05-14 06:38 UTC, roopeshsn commented on iyp/crawlers/bgptools/README.md
> +### IPV4 and IPV6 prefixes
Sure

2023-05-14 06:38 UTC, roopeshsn commented on iyp/crawlers/bgptools/README.md
> +Connect Prefix to tag node meaning that an AS has been categorized according to the tag with a label `Anycast`.
Sure

2023-05-14 06:38 UTC, roopeshsn commented on iyp/crawlers/bgptools/README.md
> +MATCH (p:Prefix {prefix: '43.249.213.0/24'})-[r:CATEGORIZED]-(t:Tag {label: 'Anycast'}) RETURN p, t
Sure

2023-05-14 06:39 UTC, roopeshsn commented on iyp/crawlers/bgptools/anycast_prefixes.py
> +        # """Fetch data and push to IYP. """
Sure

2023-05-14 06:39 UTC, roopeshsn commented on run_all_crawlers.sh
> +#BGP.Tools tags, and prefixes
Sure

2023-05-14 06:49 UTC, roopeshsn commented on iyp/crawlers/bgptools/anycast_prefixes.py
Sure

2023-05-14 06:57 UTC, roopeshsn commented on iyp/crawlers/bgptools/anycast_prefixes.py
> +        anycast_prefixes_data_url_formatted += "/master/anycatch-v4-prefixes.txt"
So you're stating that the reference_url for ipv4 prefixes should be "https://raw.githubusercontent.com/bgptools/anycast-prefixes/master/anycatch-v4-prefixes.txt" and for ipv6 it should be "https://raw.githubusercontent.com/bgptools/anycast-prefixes/master/anycatch-v6-prefixes.txt". Am I right?

2023-05-14 07:02 UTC, m-appel commented on iyp/crawlers/bgptools/anycast_prefixes.py
> +        anycast_prefixes_data_url_formatted += "/master/anycatch-v4-prefixes.txt"
Yes!

2023-05-14 09:59 UTC, roopeshsn commented on iyp/crawlers/bgptools/anycast_prefixes.py
> +        anycast_prefixes_data_url_formatted += "/master/anycatch-v4-prefixes.txt"
Alright, I will look into it!

2023-05-15 00:52 UTC, romain-fontugne commented on iyp/crawlers/bgptools/anycast_prefixes.py
> +        anycast_prefixes_data_url_formatted += "/master/anycatch-v4-prefixes.txt"
after fixing this, I will run a test before merging it

2023-05-16 01:39 UTC, roopeshsn commented on iyp/crawlers/bgptools/anycast_prefixes.py
> +        anycast_prefixes_data_url_formatted += "/master/anycatch-v4-prefixes.txt"
Yep, fixed this!

2023-05-16 02:03 UTC, merged

2023-05-16 02:04 UTC, m-appel commented
Thank you, everything looks good now.